### PR TITLE
Better error handling in Web UI

### PR DESCRIPTION
**Pull request by ColonelThirtyTwo**
The error handling in wrench primarily works by wrapping handler methods in `try { ... } catch(Exception ex} { ... }` blocks, and writing the error (and possibly the traceback) to the page.

This has multiple issues; the error handling code:

* is duplicated in every function,
* isn't standardized (some show just the exception message, some display both the message and traceback),
* displays the error to the user (tracebacks might contain sensitive information), and
* doesn't write the error to the log.

This patch removes most of the `try catch(Exception)` blocks in the web UI, and implements the error handling code in the `Global.Application_Error` method. The error handling code will log the error (with traceback) to wrench's logfile, then will display a generic "wrench has encountered an error" page (or, if localhost connected, the error plus traceback).

Note: Add `?w=1` to the URL of the GitHub diff view to ignore the indentation changes. Alternatively, use `git diff -w`.

### CODE REVIEW

**Comment by ColonelThirtyTwo** [comment]
@duncanmak @rolfbjarne

**Comment by ColonelThirtyTwo** [comment]
`WebServices` could also benefit from a similar change, but it's fairly large.

**Comment by ColonelThirtyTwo** [comment]
Looks like I missed a few places where `Exception` is thrown in order to indicate a validation failure... Will reopen when fixed.

**Comment by rolfbjarne** [comment]
1. I think you should add some sort of issue id in the error page, which is also printed to the log, *and tell people to take note of that number* so that someone can look at the logs. Otherwise people will just say "wrench is broken" and you'll have no idea what to grep for in the logs.
2. Please rebase on master (which will remove the 'Merge remote-tracking branch 'upstream/master' into error-handling' commit).
3. Please squash "fix stuff I broke" commits into the corresponding broken commits, so that the whole broken+fixed code disappears (re "Removed accidentally-commited test error page."). It just makes history easier to navigate later.

**Comment by ColonelThirtyTwo** [comment]
@rolfbjarne Done

**Pull request merged**
