### PR TITLE
Redirect to accessed page after login.

### PR DESCRIPTION
**Pull request by ColonelThirtyTwo**
@rolfbjarne @duncanmak

### CODE REVIEW

**Comment by duncanmak** [comment]
This will just add a link to the Unauthorized page, right? Can we just redirect directly to the Login page instead of showing an Unauthorized page?

**Comment by ColonelThirtyTwo** [comment]
I wanted to use the 403 Unauthorized error code, especially since `JSON.aspx` will trigger this page as well and a server-side redirect would cause anything using it to fetch the login page instead if they're unauthorized.

I'll throw up a javascript redirect.

**Comment by duncanmak** [comment]
Let's land this?

**Comment by ColonelThirtyTwo** [comment]
Done

**Pull request merged**
